General:
  num_cpu: 20
  num_gpu: 1
  results_path: mil_model_hirst
Data:
  training_dataset_path: datasets/aptc-2/aptc_2_training_datatest.csv
  test_dataset_path: datasets/aptc-2/aptc_2_test_datatest.csv
  #training_dataset_path: datasets/denmark/denmark_training_datatest.csv
  #test_dataset_path: datasets/denmark/denmark_cat_test.csv
  reactants: ['REACTANT_1', 'REACTANT_2']
  catalyst: ['CATALYST']
  activity: ['ACTIVITY']
Conformers:
  max_num_conf: 50
  energy_window: 50
Descriptors:
  num_descr: 3
Algorithm:
  type: InstanceWrapperMLPRegressor
  pooling: mean
  learning_rate: 0.001
  weight_decay: 0.001
  n_epoch: 1000
